### ISSUE TITLE
Report the correct job status

### ISSUE THREAD

**Issue by AlexV525** [k-paxian/dart-package-publisher#19] opened 2022-05-11 05:10 UTC
https://github.com/fluttercandies/flutter_wechat_assets_picker/runs/6382156800?check_suite_focus=true

The job failed, but the status report was successful, which would mislead our judgment.

**Comment by k-paxian** [comment] 2022-05-13 12:35
you are using version 1.3, this is fixed in master, you'd better stick to the `master` as a version, like `uses: k-paxian/dart-package-publisher@master`

**Closed by k-paxian** 2022-05-13 12:35 UTC

**Comment by k-paxian** [comment] 2022-05-13 12:36
duplicate of https://github.com/k-paxian/dart-package-publisher/issues/17
